"""Generate `examples/` — real artifacts from real runs.

Everything written here is produced by executing the actual crews against the
actual catalog and capturing what came out. Nothing is hand-written to look
good: if a run is mediocre, the mediocre version is what lands in the folder.
That is the point — the examples exist so quality can be judged without running
the code, which only works if they are honest.

    uv sync --all-extras
    STEWARD_PROVIDER=groq uv run python scripts/build_examples.py
"""

from __future__ import annotations

import dataclasses
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from datahub.emitter.mcp import MetadataChangeProposalWrapper  # noqa: E402
from datahub.metadata.schema_classes import (  # noqa: E402
    AuditStampClass,
    InstitutionalMemoryClass,
    InstitutionalMemoryMetadataClass,
)

from steward import scenario as s  # noqa: E402
from steward.adapter import _ENTITY_QUERY, _LINEAGE_QUERY  # noqa: E402
from steward.config import FINDING_PREFIX, Config  # noqa: E402
from steward.crew import BlastRadiusCrew, CrewResult, RootCauseCrew  # noqa: E402
from steward.fake import FakeCatalog  # noqa: E402
from steward.models import Finding  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
EX = ROOT / "examples"


def transcript(title: str, question: str, result: CrewResult, config: Config) -> str:
    st = result.stats
    lines = [
        f"# {title}",
        "",
        f"> Generated by `scripts/build_examples.py` against the demo catalog, "
        f"using `{config.provider}`. Not edited by hand.",
        "",
        "## Question",
        "",
        f"> {question}",
        "",
        "## What the crew did",
        "",
        "| Stage | Detail |",
        "| --- | --- |",
    ]
    for stage in result.trace:
        lines.append(f"| `{stage.name}` | {stage.detail} |")

    lines += [
        "",
        "## Answer",
        "",
        result.answer,
        "",
        "## Cost",
        "",
        "| Metric | Value |",
        "| --- | --- |",
        f"| Entities inspected | {st.entities_inspected} |",
        f"| Tool calls | {st.tool_calls} |",
        f"| Prior findings reused | {st.prior_findings_reused} |",
        f"| Tokens (in + out) | {st.input_tokens + st.output_tokens} |",
        f"| Wall time | {st.wall_seconds}s |",
    ]

    if result.finding:
        lines += [
            "",
            "## Finding written back to DataHub",
            "",
            "```json",
            json.dumps(dataclasses.asdict(result.finding), indent=2),
            "```",
        ]
    else:
        lines += [
            "",
            "## Finding written back to DataHub",
            "",
            "_None._ The crew declines to record when there is nothing downstream — a "
            "catalog full of vacuous findings is worse than an empty one.",
        ]
    return "\n".join(lines) + "\n"


def datahub_payload(finding: Finding) -> dict:
    """The exact aspect Steward emits, serialised.

    Findings live on the entity as `institutionalMemory` links, so they surface
    in DataHub's own UI where the next person is already looking — not in a side
    database only this tool knows about.
    """
    marker = f"{FINDING_PREFIX}#{finding.finding_id}"
    mcp = MetadataChangeProposalWrapper(
        entityUrn=finding.subject_urn,
        aspect=InstitutionalMemoryClass(
            elements=[
                InstitutionalMemoryMetadataClass(
                    url=f"https://steward.local/findings/{finding.finding_id}",
                    description=f"{marker} {finding.to_json()}",
                    createStamp=AuditStampClass(time=0, actor="urn:li:corpuser:steward"),
                )
            ]
        ),
    )
    return json.loads(json.dumps(mcp.to_obj(), default=str))


def main() -> int:
    config = Config.from_env()
    (EX / "runs").mkdir(parents=True, exist_ok=True)
    (EX / "findings").mkdir(parents=True, exist_ok=True)
    (EX / "datahub").mkdir(parents=True, exist_ok=True)

    catalog = FakeCatalog()

    print("running blast radius (cold) ...")
    cold = BlastRadiusCrew(catalog, config).run(s.DEMO_CHANGE)
    print("running blast radius again (warm) ...")
    warm = BlastRadiusCrew(catalog, config).run(s.DEMO_CHANGE)
    print("running root cause ...")
    cause = RootCauseCrew(catalog, config).run(s.DEMO_SYMPTOM)

    (EX / "runs" / "01-blast-radius-cold.md").write_text(
        transcript("Blast radius — first ask", s.DEMO_CHANGE, cold, config)
    )
    (EX / "runs" / "02-blast-radius-warm.md").write_text(
        transcript("Blast radius — same question, asked again", s.DEMO_CHANGE, warm, config)
    )
    (EX / "runs" / "03-root-cause.md").write_text(
        transcript("Root cause — ranking candidate causes", s.DEMO_SYMPTOM, cause, config)
    )

    for result, name in ((cold, "blast-radius"), (cause, "root-cause")):
        if not result.finding:
            continue
        (EX / "findings" / f"{name}.json").write_text(
            json.dumps(dataclasses.asdict(result.finding), indent=2) + "\n"
        )
        (EX / "datahub" / f"{name}-institutional-memory.json").write_text(
            json.dumps(datahub_payload(result.finding), indent=2) + "\n"
        )

    # The GraphQL Steward actually issues, so the DataHub integration can be
    # reviewed without standing up an instance.
    (EX / "datahub" / "lineage.graphql").write_text(
        "# Issued by DataHubAdapter.lineage(). Fragments are aliased per entity\n"
        "# type because `properties.name` has different nullability on Dataset\n"
        "# vs Dashboard, which makes an unaliased query a hard validation error.\n"
        + _LINEAGE_QUERY.strip()
        + "\n"
    )
    (EX / "datahub" / "entity.graphql").write_text(
        "# Issued by DataHubAdapter.get_entity().\n" + _ENTITY_QUERY.strip() + "\n"
    )

    comparison = {
        "question": s.DEMO_CHANGE,
        "first_ask": cold.stats.as_dict(),
        "second_ask": warm.stats.as_dict(),
        "note": (
            "Identical question. The second run reads the finding the first wrote "
            "into DataHub instead of re-deriving it, so it does no traversal and "
            "no model work."
        ),
    }
    (EX / "compounding-comparison.json").write_text(json.dumps(comparison, indent=2) + "\n")

    print(f"\nwrote {EX}")
    for path in sorted(EX.rglob("*")):
        if path.is_file():
            print(f"  {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
